apiVersion: v1
kind: Secret
metadata:
  name: final-postgres
  labels:
    app.kubernetes.io/name: final-postgres
type: Opaque
stringData:
  POSTGRES_USER: final
  POSTGRES_PASSWORD: final
  POSTGRES_DB: final
  DATABASE_URL: postgresql+psycopg://final:final@final-postgres:5432/final
