/** Product-owned copy. Traffic values must arrive through TrafficPort. */
export const TRAFFIC_COPY = {
  title: "Traffic",
  description: "Network-flow evidence for the current authorized cluster and namespace scope.",
  refresh: "Refresh",
  status: "Observation status",
  statusUnavailable: "Traffic flow evidence is not collected for this scope.",
  statusObserved: "Observed traffic from {sources} through the outbound cluster agent.",
  scope: "Authorized scope",
  scopeUnavailable: "The inventory scope is not fully available.",
  cluster: "Cluster",
  namespace: "Namespaces",
  freshness: "Inventory freshness",
  noNamespaces: "All namespaces",
  notObserved: "Not observed",
  summary: "Traffic summary",
  totalFlows: "Total flows",
  deniedFlows: "Denied flows",
  externalFlows: "External flows",
  relationships: "Relationships",
  relationshipsUnavailable: "Relationships are unavailable until traffic flow evidence is collected.",
  observedEmpty: "The collector observed no flows for the selected scope and filters.",
  flowCount: "{count} flows",
  flowTable: "Observed traffic flows",
  flowMap: "Flow map",
  flowDetail: "Provider-observed flow details for the authorized scope.",
  flowIdentifier: "Flow identifier",
  sourceIntegration: "Source integration",
  source: "Source",
  destination: "Destination",
  protocol: "Protocol",
  verdict: "Verdict",
  connections: "Connections",
  observedAt: "Observed at",
  external: "External",
  timeRange: "Time range",
  oneMinute: "1 minute",
  fiveMinutes: "5 minutes",
  fifteenMinutes: "15 minutes",
  oneHour: "1 hour",
  allProtocols: "All protocols",
  allVerdicts: "All verdicts",
  sort: "Sort",
  order: "Order",
  ascending: "Ascending",
  descending: "Descending",
  nextPage: "Next page",
  refreshFailed: "Traffic status could not be refreshed.",
  sources: "Traffic sources",
  sourcesDescription: "Agent-observed traffic integrations and the actions available for this cluster.",
  sourcesUnavailable: "Traffic source observations are not available for this scope.",
  sourceObservationFailed: "Traffic source status could not be refreshed.",
  active: "Active",
  available: "Available",
  notDetected: "Not detected",
  sourceError: "Observation error",
  version: "Version",
  clusterEnvironment: "Cluster environment",
  reason: "Reason",
  reasonPlaceholder: "Describe why this traffic source action is required",
  actionDescription: "Confirm the target and record a reason before this action is sent to the cluster agent.",
  confirm: "Confirm",
  commandPending: "Submitting…",
  commandFailed: "The traffic source action could not be submitted.",
  accepted: "Accepted command {id}",
} as const;
