/** Product-owned copy. Traffic values must arrive through TrafficPort. */
export const TRAFFIC_COPY = {
  title: "Traffic",
  description: "Network-flow evidence for the current authorized cluster and namespace scope.",
  refresh: "Refresh",
  status: "Observation status",
  statusUnavailable: "Traffic flow evidence is not collected for this scope.",
  scope: "Authorized scope",
  scopeUnavailable: "The inventory scope is not fully available.",
  cluster: "Cluster",
  namespace: "Namespaces",
  freshness: "Inventory freshness",
  noNamespaces: "All namespaces",
  notObserved: "Not observed",
  summary: "Traffic summary",
  totalFlows: "Total flows",
  deniedFlows: "Denied flows",
  externalFlows: "External flows",
  relationships: "Relationships",
  relationshipsUnavailable: "Relationships are unavailable until traffic flow evidence is collected.",
  refreshFailed: "Traffic status could not be refreshed.",
} as const;
