import type { ReactElement } from "react";
import { render } from "@testing-library/react";
import { vi } from "vitest";
import type { IssuesPort, IssueSummary } from "./issuesContract";
import type { IssuesSurfaceCopy } from "./issuesSurfaceContract";

const issue: IssueSummary = {
  id: "issue:workspace-1/correlation-1",
  workspaceId: "workspace-1",
  incidentId: "incident-1",
  correlationId: "correlation-1",
  clusterId: "cluster-1",
  namespace: "payments",
  resourceKind: "Deployment",
  resourceName: "checkout-api",
  symptom: "Elevated response latency",
  currentSubject: "deployment/payments/checkout-api",
  status: "investigating",
  rootCause: "Memory pressure",
  confidence: 0.86,
  supportingEvidence: ["restart spike"],
  missingEvidence: [],
  evidenceRef: "evidence-1",
  actionRoute: null,
  commandId: null,
  pullRequestUrl: null,
  errorReason: null,
  updatedAt: "2026-07-13T01:30:00Z",
};

export function issuesPort(overrides: Partial<IssuesPort> = {}): IssuesPort {
  return {
    listIssues: vi.fn().mockResolvedValue({
      clusterId: "cluster-1",
      completeness: "unknown",
      dataQualityWarnings: [],
      excludedCount: 0,
      items: [issue],
      limit: 50,
      limitReached: false,
      returned: 1,
    }),
    loadIssue: vi.fn().mockResolvedValue({
      ...issue,
      requestedClusterId: "cluster-1",
      requestedIncidentId: "incident-1",
      dataQualityWarnings: [],
      missingEvidence: [],
      supportingEvidence: ["restart spike"],
    }),
    loadEvidence: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        id: "evidence:workspace-1/7",
        correlationId: "correlation-1",
        kind: "incident.evidence",
        clusterId: "cluster-1",
        evidenceRef: "evidence-1",
        summary: "Evidence collected",
        sources: [{
          source: "kubernetes",
          summary: "Pod restart and OOMKilled events",
          schemaVersion: 1,
          collector: "cluster-agent",
          collectorVersion: "1.0.0",
          sourceVersion: null,
          queryVersion: null,
          collectedAt: null,
          evidenceKey: "kubernetes",
          sourceId: null,
          agentId: "agent-1",
          windowStart: null,
        }],
        createdAt: null,
      }],
      limit: 50,
      offset: 0,
      hasMore: false,
      nextCursor: null,
    }),
    loadReports: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        id: "rca-report:workspace-1/11",
        correlationId: "correlation-1",
        incidentId: "incident-1",
        clusterId: "cluster-1",
        namespace: "payments",
        resourceKind: "Deployment",
        resourceName: "checkout-api",
        rootCause: "Memory pressure",
        action: "Increase the memory limit after approval",
        symptom: null,
        severity: "warning",
        confidence: 0.86,
        reason: null,
        evidenceRef: "evidence-1",
        supportingEvidence: [],
        missingEvidence: [],
        secondarySymptoms: [],
        selectedCandidateId: null,
        candidates: [],
        supportingEvidenceRefs: [],
        missingEvidenceChecks: [],
        createdAt: null,
      }],
      limit: 50,
      offset: 0,
      hasMore: false,
      nextCursor: null,
    }),
    loadAuditTimeline: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        subject: "incident.detected",
        source: "dashboard-projection",
        createdAt: "2026-07-13T01:10:00Z",
        causationId: null,
        payloadSummary: { incident_id: "incident-1" },
      }],
      limit: 50,
      hasMore: false,
      nextCursor: null,
    }),
    loadRecentChanges: vi.fn().mockResolvedValue({
      incidentId: "incident-1",
      items: [],
      limit: 5,
    }),
    loadRecoveryPlan: vi.fn().mockResolvedValue({
      id: "plan-1",
      correlationId: "correlation-1",
      incidentId: "incident-1",
      evidenceRef: "evidence-1",
      status: "selection_requested",
      summary: "Choose a safe action",
      recommendedActionId: "increase-memory",
      executionRoute: "approval",
      selectionRequired: true,
      selectedActionId: null,
      selectedBy: null,
      selectedAction: null,
      candidates: [{
        id: "increase-memory",
        title: "Increase memory limit",
        description: "Raise the Deployment memory limit",
        route: "deployment.patch",
        rank: 1,
        score: 0.86,
        riskLevel: "medium",
        blastRadius: "one Deployment",
        approvalRequired: true,
        prerequisites: [],
        validationChecks: [],
        rollbackPlan: "Restore the previous limit",
        evidenceRefs: [],
      }],
    }),
    selectRecoveryAction: vi.fn().mockResolvedValue({
      kind: "accepted",
      receipt: {
        accepted: true,
        eventId: "event-1",
        correlationId: "correlation-1",
      },
    }),
    ...overrides,
  };
}

export const COPY: IssuesSurfaceCopy = {
  listLabel: "Incidents",
  listEmpty: "No incidents",
  listLoading: "Loading incidents",
  detailLabel: "Incident detail",
  detailEmpty: "Select an incident",
  detailLoading: "Loading incident detail",
  auditLabel: "Audit timeline",
  auditUnavailable: "Audit timeline unavailable",
  auditRoot: "Root event",
  auditCause: (causationId) => `Caused by ${causationId}`,
  auditPayload: "Payload summary",
  auditLoadMore: "Load more events",
  auditLoadingMore: "Loading more events",
  auditTimeUnknown: "Time unknown",
  auditTime: (value) => value,
  recentChangesLabel: "Recent changes",
  recentChangesUnavailable: "Recent changes unavailable",
  recentChangesPullRequest: "Open pull request",
  recentChangesTime: (value) => value,
  recentChangesImageBeforeLabel: "Previous image",
  recentChangesImageAfterLabel: "Deployed image",
  recentChangesCommitLabel: "Commit",
  recentChangesRepositoryLabel: "Repository",
  recentChangesWorkflowLabel: "Workflow run",
  evidenceLabel: "Evidence",
  reportsLabel: "Analysis",
  recoveryLabel: "Recovery",
  sectionLoading: "Loading section",
  sectionEmpty: "No data",
  evidenceUnavailable: "Evidence unavailable",
  reportsUnavailable: "Analysis unavailable",
  recoveryUnavailable: "Recovery unavailable",
  refresh: "Refresh",
  status: "Status",
  rootCause: "Root cause",
  recommended: "Recommended",
  approvalRequired: "Approval required",
  selectionPending: "Submitting selection",
  selectionReceived: (eventId) => `Selection received · ${eventId}`,
  genericFailure: "Unable to load",
  failureDetail: (code) => code,
  partial: (excludedCount) => `Partial · ${excludedCount}`,
};

export function renderSurface(element: ReactElement) {
  return render(element);
}
