"""Shared Gateway API bounds used by routers and conservative clients."""

from __future__ import annotations

CLUSTER_LIST_DEFAULT_LIMIT = 100
CLUSTER_LIST_MAX_LIMIT = 200

INVENTORY_RESOURCE_DEFAULT_LIMIT = 200
INVENTORY_RESOURCE_MAX_LIMIT = 1000
INVENTORY_RELATED_DEFAULT_LIMIT = 100
INVENTORY_RELATED_MAX_LIMIT = 1000
INVENTORY_EVENT_DEFAULT_LIMIT = 50
INVENTORY_EVENT_MAX_LIMIT = 200
CLUSTER_USAGE_DEFAULT_LIMIT = 288
CLUSTER_USAGE_MAX_LIMIT = 2000

RESOURCE_GRAPH_DEFAULT_NODE_LIMIT = 200
RESOURCE_GRAPH_MAX_NODE_LIMIT = 200
RESOURCE_GRAPH_DEFAULT_EDGE_LIMIT = 1000
RESOURCE_GRAPH_MAX_EDGE_LIMIT = 2000

DEAD_LETTER_DEFAULT_LIMIT = 50
DEAD_LETTER_MAX_LIMIT = 100

DASHBOARD_RCA_DEFAULT_LIMIT = 50
DASHBOARD_RCA_MAX_LIMIT = 100
RESOURCE_ISSUE_DEFAULT_LIMIT = 25

RCA_QUERY_DEFAULT_LIMIT = 50
RCA_QUERY_MAX_LIMIT = 200

ALERT_EVENT_DEFAULT_LIMIT = 100
ALERT_EVENT_MAX_LIMIT = 200

AUDIT_TIMELINE_DEFAULT_LIMIT = 50
AUDIT_TIMELINE_MAX_LIMIT = 200

APPLICATION_LIST_DEFAULT_LIMIT = 100
APPLICATION_LIST_MAX_LIMIT = 200
APPLICATION_DEPLOYMENT_DEFAULT_LIMIT = 100
APPLICATION_DEPLOYMENT_MAX_LIMIT = 500
APPLICATION_WORKFLOW_RUN_DEFAULT_LIMIT = 100
APPLICATION_WORKFLOW_RUN_MAX_LIMIT = 500

RELEASE_PLAN_DEFAULT_LIMIT = 100
RELEASE_PLAN_MAX_LIMIT = 500
RELEASE_RUN_DEFAULT_LIMIT = 50
RELEASE_RUN_MAX_LIMIT = 200
RELEASE_RUN_SUMMARY_LIMIT = 200
RELEASE_AUDIT_DEFAULT_LIMIT = 200
RELEASE_AUDIT_EXPORT_DEFAULT_LIMIT = 500
RELEASE_AUDIT_MAX_LIMIT = 1000

CHANGE_TIMELINE_MIN_BUCKET_MS = 1_000
CHANGE_TIMELINE_MAX_BUCKET_MS = 3_600_000
CHANGE_TIMELINE_MAX_RANGE_MS = 24 * 60 * 60 * 1_000
CHANGE_TIMELINE_MAX_BUCKETS = 1_440
CHANGE_TIMELINE_MAX_EPOCH_MS = 253_402_300_799_000
