/** Product-owned UI copy. Runtime values always arrive through HelmPort. */
export const HELM_COPY = {
  title: "Helm releases",
  description: "Inventory-observed Helm release metadata for the current authorized scope.",
  searchLabel: "Filter releases",
  searchPlaceholder: "Name, namespace, or status",
  releaseName: "Name",
  cluster: "Cluster",
  namespace: "Namespace",
  chart: "Chart",
  status: "Status",
  revision: "Revision",
  observed: "Observed",
  unavailableValue: "Not observed",
  noReleases: "No Helm release storage metadata was observed for this scope.",
  partialCoverage: "Release discovery is incomplete for this scope.",
  unavailableCoverage: "Release discovery is unavailable for this scope.",
  coverageReasonAuthorization: "The current authorization scope does not permit release discovery.",
  coverageReasonUnavailable: "A current inventory observation is not available for this scope.",
  coverageReasonPartial: "Some inventory observations are incomplete for this scope.",
  coverageReasonGeneric: "The source did not provide complete release discovery evidence.",
  permissionDenied: "Your account is not authorized to read Helm release metadata for this scope.",
  manifestUnavailable: "A safe manifest source is not available for this release.",
  valuesUnavailable: "A safe values source is not available for this release.",
  resourceHealthUnavailable: "Owned-resource health has not been correlated for this release.",
  commandsUnavailable: "Helm commands are not available for this release.",
  featureUnavailable: "This release capability is not available from the current source.",
  detailTitle: "Release details",
  backToReleases: "Back to releases",
  history: "Observed revisions",
  integrations: "Integration availability",
  storage: "Storage record",
  resourceHealth: "Resource health",
  manifest: "Manifest",
  values: "Values",
  ownedResources: "Owned resources",
  commands: "Commands",
  scope: "Scope",
} as const;
