import { useMemo } from "react";
import { useI18n, type TranslationFunction } from "../../shared/i18n";

/** Product-owned UI copy. Runtime values always arrive through HelmPort. */
export function createHelmCopy(t: TranslationFunction) {
  return {
    title: t("helm.ui.title"),
    install: t("helm.ui.install"),
    installTitle: t("helm.ui.installTitle"),
    installDescription: t("helm.ui.installDescription"),
    installTarget: t("helm.ui.installTarget"),
    installReleaseName: t("helm.ui.installReleaseName"),
    installConfirm: t("helm.ui.installConfirm"),
    installPending: t("helm.ui.installPending"),
    installFailed: t("helm.ui.installFailed"),
    installTargetsFailed: t("helm.ui.installTargetsFailed"),
    refresh: t("common.action.refresh"),
    refreshPending: t("helm.ui.refreshPending"),
    refreshSucceeded: t("helm.ui.refreshSucceeded"),
    refreshFailed: t("helm.ui.refreshFailed"),
    refreshReconnecting: t("helm.ui.refreshReconnecting"),
    refreshCancelled: t("helm.ui.refreshCancelled"),
    description: t("helm.ui.description"),
    chartSources: t("helm.ui.chartSources"),
    artifactHub: t("helm.ui.artifactHub"),
    artifactHubDescription: t("helm.ui.artifactHubDescription"),
    artifactHubSearchLabel: t("helm.ui.artifactHubSearchLabel"),
    artifactHubSearchPlaceholder: t("helm.ui.artifactHubSearchPlaceholder"),
    artifactHubSearch: t("common.action.search"),
    artifactHubFailed: t("helm.ui.artifactHubFailed"),
    artifactHubEmpty: t("helm.ui.artifactHubEmpty"),
    artifactHubOfficial: t("helm.ui.artifactHubOfficial"),
    artifactHubVerified: t("helm.ui.artifactHubVerified"),
    artifactHubSigned: t("helm.ui.artifactHubSigned"),
    artifactHubDetailLoading: t("helm.ui.artifactHubDetailLoading"),
    chartSourcesDescription: t("helm.ui.chartSourcesDescription"),
    chartCatalog: t("helm.ui.chartCatalog"),
    chartCatalogDescription: t("helm.ui.chartCatalogDescription"),
    chartCatalogSearchLabel: t("helm.ui.chartCatalogSearchLabel"),
    chartCatalogSearchPlaceholder: t("helm.ui.chartCatalogSearchPlaceholder"),
    chartCatalogSource: t("helm.ui.chartCatalogSource"),
    chartCatalogAllSources: t("helm.ui.chartCatalogAllSources"),
    chartCatalogProvider: t("helm.ui.chartCatalogProvider"),
    chartCatalogAllProviders: t("helm.ui.chartCatalogAllProviders"),
    chartCatalogAllVersions: t("helm.ui.chartCatalogAllVersions"),
    chartCatalogSearch: t("helm.ui.chartCatalogSearch"),
    chartCatalogLoading: t("helm.ui.chartCatalogLoading"),
    chartCatalogFailed: t("helm.ui.chartCatalogFailed"),
    chartCatalogPartial: t("helm.ui.chartCatalogPartial"),
    chartCatalogEmpty: t("helm.ui.chartCatalogEmpty"),
    chartCatalogDetailLoading: t("helm.ui.chartCatalogDetailLoading"),
    chartCatalogDetailFailed: t("helm.ui.chartCatalogDetailFailed"),
    chartCatalogVersions: t("helm.ui.chartCatalogVersions"),
    chartCatalogValuesSchema: t("helm.ui.chartCatalogValuesSchema"),
    chartCatalogValuesSchemaUnavailable: t("helm.ui.chartCatalogValuesSchemaUnavailable"),
    chartCatalogInstallUnavailable: t("helm.ui.chartCatalogInstallUnavailable"),
    chartCatalogInstall: (name: string) => t("helm.ui.chartCatalogInstall", { name }),
    chartSourcesLoading: t("helm.ui.chartSourcesLoading"),
    chartSourcesEmpty: t("helm.ui.chartSourcesEmpty"),
    chartSourcesUnavailable: t("helm.ui.chartSourcesUnavailable"),
    chartSourcesFailed: t("helm.ui.chartSourcesFailed"),
    chartSourcesForbidden: t("helm.ui.chartSourcesForbidden"),
    chartSourcesRetry: t("helm.ui.chartSourcesRetry"),
    chartSourcesLoadMore: t("helm.ui.chartSourcesLoadMore"),
    chartSourcesLoadMoreFailed: t("helm.ui.chartSourcesLoadMoreFailed"),
    chartSourcesRegister: t("helm.ui.chartSourcesRegister"),
    chartSourcesRegisterDescription: t("helm.ui.chartSourcesRegisterDescription"),
    chartSourcesRegisterSave: t("helm.ui.chartSourcesRegisterSave"),
    chartSourcesRegisterPending: t("helm.ui.chartSourcesRegisterPending"),
    chartSourcesRegisterFailed: t("helm.ui.chartSourcesRegisterFailed"),
    chartSourcesRegisterForbidden: t("helm.ui.chartSourcesRegisterForbidden"),
    chartSourceActions: t("helm.ui.chartSourceActions"),
    chartSourceRefreshButton: (name: string) => t("helm.ui.chartSourceRefreshButton", { name }),
    chartSourceRefreshFailed: t("helm.ui.chartSourceRefreshFailed"),
    chartSourceDelete: t("helm.ui.chartSourceDelete"),
    chartSourceDeleteButton: (name: string) => t("helm.ui.chartSourceDeleteButton", { name }),
    chartSourceDeleteDescription: t("helm.ui.chartSourceDeleteDescription"),
    chartSourceDeleteConfirm: t("helm.ui.chartSourceDeleteConfirm"),
    chartSourceDeletePending: t("helm.ui.chartSourceDeletePending"),
    chartSourceDeleteFailed: t("helm.ui.chartSourceDeleteFailed"),
    chartSourceDeleteForbidden: t("helm.ui.chartSourceDeleteForbidden"),
    chartSourceDeleteNotFound: t("helm.ui.chartSourceDeleteNotFound"),
    chartSourceDeleteConflict: t("helm.ui.chartSourceDeleteConflict"),
    chartSourceType: t("helm.ui.chartSourceType"),
    chartSourceRepository: t("helm.ui.chartSourceRepository"),
    chartSourceOci: t("helm.ui.chartSourceOci"),
    chartSourceName: t("helm.ui.chartSourceName"),
    chartSourceReference: t("helm.ui.chartSourceReference"),
    chartSourceReferenceRepositoryHint: t("helm.ui.chartSourceReferenceRepositoryHint"),
    chartSourceReferenceOciHint: t("helm.ui.chartSourceReferenceOciHint"),
    chartSourceAuthentication: t("helm.ui.chartSourceAuthentication"),
    chartSourceAuthenticationNone: t("helm.ui.chartSourceAuthenticationNone"),
    chartSourceAuthenticationBearer: t("helm.ui.chartSourceAuthenticationBearer"),
    chartSourceAuthenticationBasic: t("helm.ui.chartSourceAuthenticationBasic"),
    chartSourceUsername: t("helm.ui.chartSourceUsername"),
    chartSourcePassword: t("helm.ui.chartSourcePassword"),
    chartSourceBearerToken: t("helm.ui.chartSourceBearerToken"),
    chartSourceStatus: t("helm.ui.chartSourceStatus"),
    chartSourceCredentials: t("helm.ui.chartSourceCredentials"),
    chartSourceCredentialsConfigured: t("helm.ui.chartSourceCredentialsConfigured"),
    chartSourceCredentialsNone: t("helm.ui.chartSourceCredentialsNone"),
    chartSourceObserved: t("helm.ui.chartSourceObserved"),
    chartSourceCancel: t("common.action.cancel"),
    searchLabel: t("helm.ui.searchLabel"),
    searchPlaceholder: t("helm.ui.searchPlaceholder"),
    releaseName: t("helm.ui.releaseName"),
    cluster: t("helm.ui.cluster"),
    namespace: t("helm.ui.namespace"),
    chart: t("helm.ui.chart"),
    upgradeAvailability: t("helm.upgrade.action"),
    upgradeAvailableSuffix: t("helm.ui.upgradeAvailableSuffix"),
    upgradeUpToDate: t("helm.ui.upgradeUpToDate"),
    upgradeSourceUnavailable: t("helm.ui.upgradeSourceUnavailable"),
    upgradeSource: t("helm.ui.upgradeSource"),
    upgradeVersions: t("helm.ui.upgradeVersions"),
    upgradeVersionTransition: t("helm.ui.upgradeVersionTransition"),
    upgradeVersionsTruncated: t("helm.ui.upgradeVersionsTruncated"),
    status: t("helm.ui.status"),
    revision: t("helm.ui.revision"),
    observed: t("helm.ui.observed"),
    unavailableValue: t("helm.ui.unavailableValue"),
    noReleases: t("helm.ui.noReleases"),
    partialCoverage: t("helm.ui.partialCoverage"),
    unavailableCoverage: t("helm.ui.unavailableCoverage"),
    coverageReasonAuthorization: t("helm.ui.coverageReasonAuthorization"),
    coverageReasonUnavailable: t("helm.ui.coverageReasonUnavailable"),
    coverageReasonPartial: t("helm.ui.coverageReasonPartial"),
    coverageReasonGeneric: t("helm.ui.coverageReasonGeneric"),
    permissionDenied: t("helm.ui.permissionDenied"),
    sessionUnavailable: t("helm.ui.sessionUnavailable"),
    requestInvalid: t("helm.ui.requestInvalid"),
    responseInvalid: t("helm.ui.responseInvalid"),
    releaseNotFound: t("helm.ui.releaseNotFound"),
    connectionUnavailable: t("helm.ui.connectionUnavailable"),
    rateLimited: t("helm.ui.rateLimited"),
    requestFailed: t("helm.ui.requestFailed"),
    manifestUnavailable: t("helm.ui.manifestUnavailable"),
    valuesUnavailable: t("helm.ui.valuesUnavailable"),
    resourceHealthUnavailable: t("helm.ui.resourceHealthUnavailable"),
    resourceSnapshotUnavailable: t("helm.ui.resourceSnapshotUnavailable"),
    ownedResourcesPartial: t("helm.ui.ownedResourcesPartial"),
    ownedResourcesTruncated: t("helm.ui.ownedResourcesTruncated"),
    ownedResourcesEmpty: t("helm.ui.ownedResourcesEmpty"),
    commandsUnavailable: t("helm.ui.commandsUnavailable"),
    rollback: t("helm.ui.rollback"),
    rollbackTitle: t("helm.ui.rollbackTitle"),
    rollbackDescription: t("helm.ui.rollbackDescription"),
    rollbackRevision: t("helm.ui.rollbackRevision"),
    rollbackConfirm: t("helm.ui.rollbackConfirm"),
    rollbackFailed: t("helm.ui.rollbackFailed"),
    rollbackReason: (name: string, revision: number) => t("helm.ui.rollbackReason", { name, revision }),
    uninstall: t("helm.ui.uninstall"),
    uninstallTitle: t("helm.ui.uninstallTitle"),
    uninstallDescription: t("helm.ui.uninstallDescription"),
    uninstallConfirm: t("helm.ui.uninstallConfirm"),
    uninstallFailed: t("helm.ui.uninstallFailed"),
    uninstallReason: (name: string) => t("helm.ui.uninstallReason", { name }),
    operationPending: t("helm.ui.operationPending"),
    operationForbidden: t("helm.ui.operationForbidden"),
    operationStale: t("helm.ui.operationStale"),
    operationStreamUnavailable: t("helm.ui.operationStreamUnavailable"),
    operationDiff: (
      cluster: string,
      namespace: string,
      release: string,
      expectedRevision: number,
      rollbackRevision: number | null,
    ) => t(
      rollbackRevision === null
        ? "helm.ui.operationDiff"
        : "helm.ui.operationDiffWithRollback",
      {
        cluster,
        namespace,
        release,
        expectedRevision,
        ...(rollbackRevision === null ? {} : { rollbackRevision }),
      },
    ),
    artifacts: t("helm.ui.artifacts"),
    artifactDescription: t("helm.ui.artifactDescription"),
    manifestAction: t("helm.ui.manifestAction"),
    valuesAction: t("helm.ui.valuesAction"),
    manifestDiffAction: t("helm.ui.manifestDiffAction"),
    valuesDiffAction: t("helm.ui.valuesDiffAction"),
    notesDiffAction: t("helm.ui.notesDiffAction"),
    hooksDiffAction: t("helm.ui.hooksDiffAction"),
    resourcesDiffAction: t("helm.ui.resourcesDiffAction"),
    primaryRevision: t("helm.ui.primaryRevision"),
    comparisonRevision: t("helm.ui.comparisonRevision"),
    allValues: t("helm.ui.allValues"),
    artifactReading: t("helm.ui.artifactReading"),
    artifactFailed: t("helm.ui.artifactFailed"),
    artifactStreamUnavailable: t("helm.ui.artifactStreamUnavailable"),
    artifactTruncated: t("helm.ui.artifactTruncated"),
    artifactRedacted: t("helm.ui.artifactRedacted"),
    artifactEmpty: t("helm.ui.artifactEmpty"),
    hooksAdded: t("helm.ui.hooksAdded"),
    hooksRemoved: t("helm.ui.hooksRemoved"),
    hooksModified: t("helm.ui.hooksModified"),
    hooksUnchanged: t("helm.ui.hooksUnchanged"),
    hookManifestChanged: t("helm.ui.hookManifestChanged"),
    hookParseError: t("helm.ui.hookParseError"),
    hookParseErrors: t("helm.ui.hookParseErrors"),
    resourcesAdded: t("helm.ui.resourcesAdded"),
    resourcesRemoved: t("helm.ui.resourcesRemoved"),
    resourcesModified: t("helm.ui.resourcesModified"),
    resourcesUnchanged: t("helm.ui.resourcesUnchanged"),
    resourceParseError: t("helm.ui.resourceParseError"),
    resourceParseErrors: t("helm.ui.resourceParseErrors"),
    changedFields: t("helm.ui.changedFields"),
    previousValue: t("helm.ui.previousValue"),
    currentValue: t("helm.ui.currentValue"),
    events: t("helm.ui.events"),
    weight: t("helm.ui.weight"),
    deletePolicies: t("helm.ui.deletePolicies"),
    outputLogPolicies: t("helm.ui.outputLogPolicies"),
    featureUnavailable: t("helm.ui.featureUnavailable"),
    detailTitle: t("helm.ui.detailTitle"),
    backToReleases: t("helm.ui.backToReleases"),
    history: t("helm.ui.history"),
    integrations: t("helm.ui.integrations"),
    storage: t("helm.ui.storage"),
    resourceHealth: t("helm.ui.resourceHealth"),
    resourceCount: t("helm.ui.resourceCount"),
    resourceKind: t("helm.ui.resourceKind"),
    resourceName: t("helm.ui.resourceName"),
    health: t("helm.ui.health"),
    manifest: t("helm.ui.manifest"),
    values: t("helm.ui.values"),
    ownedResources: t("helm.ui.ownedResources"),
    commands: t("helm.ui.commands"),
    scope: t("helm.ui.scope"),
  } as const;
}

export type HelmCopy = ReturnType<typeof createHelmCopy>;

export function useHelmCopy(): HelmCopy {
  const { t } = useI18n();
  return useMemo(() => createHelmCopy(t), [t]);
}
