/** Product-owned UI copy. Runtime values always arrive through HelmPort. */
export const HELM_COPY = {
  title: "Helm releases",
  refresh: "Refresh",
  refreshPending: "Refreshing Helm releases.",
  refreshSucceeded: "Helm releases refreshed.",
  refreshFailed: "Could not refresh Helm releases. Showing the last observed result.",
  refreshReconnecting: "Reconnecting Helm release data.",
  refreshCancelled: "Helm release refresh was cancelled.",
  description: "Inventory-observed Helm release metadata for the current authorized scope.",
  searchLabel: "Filter releases",
  searchPlaceholder: "Name, namespace, or status",
  releaseName: "Name",
  cluster: "Cluster",
  namespace: "Namespace",
  chart: "Chart",
  status: "Status",
  revision: "Revision",
  observed: "Observed",
  unavailableValue: "Not observed",
  noReleases: "No Helm release storage metadata was observed for this scope.",
  partialCoverage: "Release discovery is incomplete for this scope.",
  unavailableCoverage: "Release discovery is unavailable for this scope.",
  coverageReasonAuthorization: "The current authorization scope does not permit release discovery.",
  coverageReasonUnavailable: "A current inventory observation is not available for this scope.",
  coverageReasonPartial: "Some inventory observations are incomplete for this scope.",
  coverageReasonGeneric: "The source did not provide complete release discovery evidence.",
  permissionDenied: "Your account is not authorized to read Helm release metadata for this scope.",
  sessionUnavailable: "Your current sign-in session cannot access Helm release metadata for this scope.",
  requestInvalid: "The Helm release request could not be prepared. Refresh the page and try again.",
  responseInvalid: "Helm release data could not be read safely. Try again shortly.",
  releaseNotFound: "The requested Helm release metadata is not available in this scope.",
  connectionUnavailable: "Helm release data cannot be reached right now. Check the connection and try again.",
  rateLimited: "Helm release data is temporarily rate limited. Try again shortly.",
  requestFailed: "Helm release data could not be loaded. Try again shortly.",
  manifestUnavailable: "A safe manifest source is not available for this release.",
  valuesUnavailable: "A safe values source is not available for this release.",
  resourceHealthUnavailable: "Owned-resource health has not been correlated for this release.",
  resourceSnapshotUnavailable: "A complete owned-resource observation is not available for this release.",
  ownedResourcesPartial: "Owned-resource observation is incomplete.",
  ownedResourcesTruncated: "The owned-resource result reached the configured query limit.",
  ownedResourcesEmpty: "No currently observed resources carry this release's exact Helm ownership metadata.",
  commandsUnavailable: "Helm commands are not available for this release.",
  featureUnavailable: "This release capability is not available from the current source.",
  detailTitle: "Release details",
  backToReleases: "Back to releases",
  history: "Observed revisions",
  integrations: "Integration availability",
  storage: "Storage record",
  resourceHealth: "Resource health",
  resourceCount: "Resources",
  resourceKind: "Kind",
  resourceName: "Resource",
  health: "Health",
  manifest: "Manifest",
  values: "Values",
  ownedResources: "Owned resources",
  commands: "Commands",
  scope: "Scope",
} as const;
