apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsia.fullname" . }}
  labels:
    {{- include "opsia.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opsia.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
