/** Product-owned Cost copy. Monetary values arrive only through CostPort. */
export const COST_COPY = {
  title: "Cost",
  description: "Billing and allocation evidence for the current authorized cluster scope.",
  refresh: "Refresh",
  refreshPending: "Refreshing Cost data.",
  refreshSucceeded: "Cost data refreshed.",
  refreshReconnecting: "Reconnecting Cost data.",
  refreshCancelled: "Cost refresh was cancelled.",
  status: "Observation status",
  statusUnavailable: "Cost observation is not integrated for this authorized scope.",
  scope: "Authorized scope",
  scopeUnavailable: "The inventory scope is not fully available.",
  scopeReasonUnavailable: "Some selected clusters have no current inventory snapshot.",
  scopeReasonPartial: "Some selected inventory snapshots are incomplete.",
  scopeReasonAuthorization: "No authorized cluster scope is available.",
  scopeReasonGeneric: "Some scope evidence is unavailable.",
  scopeSelectionUnavailable: "The selected cluster scope cannot be resolved.",
  allNamespaces: "All namespaces",
  notObserved: "Not observed",
  hourlyCost: "Current hourly cost",
  monthlyProjection: "Monthly projection",
  storageCost: "Storage cost",
  idleCost: "Idle cost",
  efficiency: "Allocation efficiency",
  savings: "Savings recommendations",
  summary: "Cost summary",
  refreshFailed: "Cost status could not be refreshed.",
} as const;
