import type { PhysicalTopologySnapshot } from "../../features/resources/physicalTopologyContract";

export const PHYSICAL_TOPOLOGY: PhysicalTopologySnapshot = {
  clusterId: "cluster-1",
  clusterProjectionRevision: 42,
  servers: [
    {
      id: "node:worker-a",
      name: "worker-a",
      cpuPercent: 68,
      memoryPercent: 54,
      cpuMillicores: 680,
      memoryMebibytes: 1106,
      allocatableCpuMillicores: 1000,
      allocatableMemoryMebibytes: 2048,
      podCapacity: 110,
      status: "Ready",
      matchedPodCount: 2,
      totalPodCount: 18,
      matchedPodCountCompleteness: "exact",
      totalPodCountCompleteness: "exact",
    },
    {
      id: "node:worker-b",
      name: "worker-b",
      cpuPercent: null,
      memoryPercent: 81,
      cpuMillicores: null,
      memoryMebibytes: 3318,
      allocatableCpuMillicores: null,
      allocatableMemoryMebibytes: 4096,
      podCapacity: 110,
      status: "Ready",
      matchedPodCount: 0,
      totalPodCount: 1,
      matchedPodCountCompleteness: "exact",
      totalPodCountCompleteness: "exact",
    },
  ],
  pods: [
    {
      id: "pod:shop/checkout-api-0",
      name: "checkout-api-0",
      namespace: "shop",
      serverId: "node:worker-a",
      usagePercent: 12,
      cpuMillicores: 30,
      cpuRequestMillicores: 100,
      memoryMebibytes: 64,
      memoryRequestMebibytes: 128,
      cpuLimitMillicores: 500,
      memoryLimitMebibytes: 1024,
      phase: "CrashLoopBackOff",
      health: "critical",
      restartCount: 8,
      matchesFilter: true,
    },
    {
      id: "pod:shop/orders-api-0",
      name: "orders-api-0",
      namespace: "shop",
      serverId: "node:worker-a",
      usagePercent: 91,
      cpuMillicores: 240,
      cpuRequestMillicores: 250,
      memoryMebibytes: 196,
      memoryRequestMebibytes: 256,
      cpuLimitMillicores: 500,
      memoryLimitMebibytes: 512,
      phase: "Running",
      health: "healthy",
      restartCount: 0,
      matchesFilter: false,
    },
    {
      id: "pod:ops/telemetry-0",
      name: "telemetry-0",
      namespace: "ops",
      serverId: "node:worker-b",
      usagePercent: null,
      cpuMillicores: null,
      cpuRequestMillicores: null,
      memoryMebibytes: null,
      memoryRequestMebibytes: null,
      cpuLimitMillicores: null,
      memoryLimitMebibytes: null,
      phase: "Pending",
      health: "unknown",
      restartCount: 0,
      matchesFilter: false,
    },
  ],
  truncatedByServer: { "node:worker-a": 16 },
  unassignedTruncatedCount: 0,
  counts: {
    filteredCount: 2,
    unfilteredCount: 19,
    filteredCountCompleteness: "exact",
    unfilteredCountCompleteness: "exact",
  },
  projectionCompleteness: "exact",
  metricsCompleteness: "partial",
  metricsObservedAt: "2026-07-12T10:00:00.000Z",
  partialReasonCodes: ["pod_usage_requests_unavailable"],
  snapshot: {
    snapshotRevision: 42,
    authorizationRevision: "auth-1",
    filterFingerprint: "filter-1",
    observedAt: "2026-07-12T10:00:00.000Z",
    stale: false,
    partialReasonCodes: [],
  },
};
