import type { ReactElement } from "react";
import { render } from "@testing-library/react";
import { vi } from "vitest";
import type { IssuesPort, IssueSummary } from "./issuesContract";
import type { IssuesSurfaceCopy } from "./issuesSurfaceContract";

const issue: IssueSummary = {
  id: "issue:workspace-1/correlation-1",
  workspaceId: "workspace-1",
  incidentId: "incident-1",
  correlationId: "correlation-1",
  clusterId: "cluster-1",
  namespace: "payments",
  resourceKind: "Deployment",
  resourceName: "checkout-api",
  symptom: "Elevated response latency",
  currentSubject: "deployment/payments/checkout-api",
  status: "investigating",
  rootCause: "Memory pressure",
  confidence: 0.86,
  supportingEvidence: ["restart spike"],
  missingEvidence: [],
  evidenceRef: "evidence-1",
  actionRoute: null,
  commandId: null,
  pullRequestUrl: null,
  errorReason: null,
  updatedAt: "2026-07-13T01:30:00Z",
  situationSummary: null,
  recommendedActionSummary: null,
  evidenceSummary: null,
  evidenceBundleSummary: null,
};

export function issuesPort(overrides: Partial<IssuesPort> = {}): IssuesPort {
  return {
    listIssues: vi.fn().mockResolvedValue({
      clusterId: "cluster-1",
      completeness: "unknown",
      dataQualityWarnings: [],
      excludedCount: 0,
      items: [issue],
      limit: 50,
      limitReached: false,
      returned: 1,
    }),
    loadIssue: vi.fn().mockResolvedValue({
      ...issue,
      requestedClusterId: "cluster-1",
      requestedIncidentId: "incident-1",
      dataQualityWarnings: [],
      missingEvidence: [],
      supportingEvidence: ["restart spike"],
    }),
    loadEvidence: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        id: "evidence:workspace-1/7",
        correlationId: "correlation-1",
        kind: "incident.evidence",
        clusterId: "cluster-1",
        evidenceRef: "evidence-1",
        summary: "Evidence collected",
        sources: [{
          source: "kubernetes",
          summary: "Pod restart and OOMKilled events",
          schemaVersion: 1,
          collector: "cluster-agent",
          collectorVersion: "1.0.0",
          sourceVersion: null,
          queryVersion: null,
          collectedAt: null,
          evidenceKey: "kubernetes",
          sourceId: null,
          agentId: "agent-1",
          windowStart: null,
        }],
        createdAt: null,
      }],
      limit: 50,
      offset: 0,
      hasMore: false,
      nextCursor: null,
    }),
    loadReports: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        id: "rca-report:workspace-1/11",
        correlationId: "correlation-1",
        incidentId: "incident-1",
        clusterId: "cluster-1",
        namespace: "payments",
        resourceKind: "Deployment",
        resourceName: "checkout-api",
        rootCause: "Memory pressure",
        action: "Increase the memory limit after approval",
        symptom: null,
        severity: "warning",
        confidence: 0.86,
        reason: null,
        evidenceRef: "evidence-1",
        supportingEvidence: [],
        missingEvidence: [],
        secondarySymptoms: [],
        selectedCandidateId: null,
        candidates: [],
        supportingEvidenceRefs: [],
        missingEvidenceChecks: [],
        narrative: {
          locale: "ko",
          executiveSummary: "The Pod repeatedly restarted after exceeding its memory limit.",
          impact: "API processing may have been unstable during restarts.",
          reasoning: "OOMKilled and memory usage evidence support the same cause.",
          recommendedAction: "Review memory usage and apply an approved limit adjustment.",
          recurrencePrevention: ["Monitor OOMKilled together with memory utilization."],
          limitations: ["Request error-rate evidence was not collected."],
        },
        narrativeStatus: "generated",
        createdAt: null,
      }],
      limit: 50,
      offset: 0,
      hasMore: false,
      nextCursor: null,
    }),
    loadAuditTimeline: vi.fn().mockResolvedValue({
      correlationId: "correlation-1",
      items: [{
        eventId: "event-incident-1",
        subject: "incident.detected",
        source: "dashboard-projection",
        createdAt: "2026-07-13T01:10:00Z",
        causationId: null,
        journeyStage: "alert",
        payloadSummary: { incident_id: "incident-1" },
      }],
      limit: 50,
      hasMore: false,
      nextCursor: null,
    }),
    loadRecentChanges: vi.fn().mockResolvedValue({
      incidentId: "incident-1",
      items: [],
      limit: 5,
    }),
    loadRecoveryPlan: vi.fn().mockResolvedValue({
      id: "plan-1",
      correlationId: "correlation-1",
      incidentId: "incident-1",
      evidenceRef: "evidence-1",
      status: "selection_requested",
      summary: "Choose a safe action",
      recommendedActionId: "increase-memory",
      executionRoute: "approval",
      selectionRequired: true,
      selectedActionId: null,
      selectedBy: null,
      selectedAction: null,
      candidates: [{
        id: "increase-memory",
        title: "Increase memory limit",
        description: "Raise the Deployment memory limit",
        route: "deployment.patch",
        rank: 1,
        score: 0.86,
        riskLevel: "medium",
        blastRadius: "one Deployment",
        approvalRequired: true,
        prerequisites: [],
        validationChecks: [],
        rollbackPlan: "Restore the previous limit",
        evidenceRefs: [],
        recommendationReason: null,
        expectedOutcome: null,
        riskExplanation: null,
        rollbackReason: null,
      }],
    }),
    selectRecoveryAction: vi.fn().mockResolvedValue({
      kind: "accepted",
      receipt: {
        accepted: true,
        eventId: "event-1",
        correlationId: "correlation-1",
      },
    }),
    ...overrides,
  };
}

export const COPY: IssuesSurfaceCopy = {
  listLabel: "Incidents",
  listEmpty: "No incidents",
  listLoading: "Loading incidents",
  listCount: (count) => String(count),
  listBrowseResources: "Browse resources",
  listBrowseAlerts: "Review alerts",
  detailLabel: "Incident detail",
  detailEmpty: "Select an incident",
  detailLoading: "Loading incident detail",
  detailClose: "Close incident detail",
  detailExpand: "Open incident detail full screen",
  detailCollapse: "Show incident list and detail",
  auditLabel: "Audit timeline",
  auditUnavailable: "Audit timeline unavailable",
  auditRoot: "Root event",
  auditCause: (causationId) => `Caused by ${causationId}`,
  auditEvent: (subject) => subject,
  auditStage: (stage) => stage,
  auditPayload: "Payload summary",
  auditLoadMore: "Load more events",
  auditLoadingMore: "Loading more events",
  auditTimeUnknown: "Time unknown",
  auditTime: (value) => value,
  recentChangesLabel: "Recent changes",
  recentChangesUnavailable: "Recent changes unavailable",
  recentChangesPullRequest: "Open pull request",
  recentChangesTime: (value) => value,
  recentChangesImageBeforeLabel: "Previous image",
  recentChangesImageAfterLabel: "Deployed image",
  recentChangesCommitLabel: "Commit",
  recentChangesRepositoryLabel: "Repository",
  recentChangesWorkflowLabel: "Workflow run",
  evidenceLabel: "Evidence",
  evidenceRecordLabel: (summary) => summary,
  evidenceKindLabel: (kind) => kind,
  evidenceSourceLabel: (source) => source,
  evidenceCollectorLabel: (collector) => collector,
  evidenceSummaryLabel: (_source, summary) => summary,
  reportsLabel: "Analysis",
  reportsEmpty: "Analysis is still being generated",
  recoveryLabel: "Recovery",
  sectionLoading: "Loading section",
  sectionEmpty: "No data",
  evidenceUnavailable: "Evidence unavailable",
  reportsUnavailable: "Analysis unavailable",
  recoveryUnavailable: "Recovery unavailable",
  refresh: "Refresh",
  status: "Status",
  statusLabel: (status) => status,
  lifecycleOpen: "Open",
  lifecycleClosed: "Closed",
  actionReviewRequired: "Review action",
  actionReviewAgainRequired: "Review action again",
  actionAutoApprovalAvailable: "Auto approval available",
  scope: "Scope",
  namespaceSuffix: "namespace",
  severityLabel: (severity) => severity,
  causeLabel: (cause) => cause,
  target: "Target",
  updated: "Updated",
  confidence: "Confidence",
  symptom: "Symptom",
  supportingEvidence: "Supporting evidence",
  missingEvidence: "More evidence required",
  rootCause: "Root cause",
  recommended: "Recommended",
  narrativeLabel: "AI-authored analysis",
  narrativeSummary: "Executive summary",
  narrativeImpact: "Impact",
  narrativeReasoning: "Reasoning",
  narrativeRecommendedAction: "Recommended action",
  narrativeRecurrencePrevention: "Recurrence prevention",
  narrativeLimitations: "Limitations",
  approvalRequired: "Approval required",
  recoveryProgressAccepted: "Approval received · waiting for agent dispatch",
  recoveryProgressApproval: "Approval",
  recoveryProgressApprovalWaiting: "Review recovery action",
  recoveryProgressCompletion: "Complete",
  recoveryProgressExecution: "Agent execution",
  recoveryProgressFailed: "Recovery failed",
  recoveryProgressLabel: "Recovery progress",
  recoveryProgressLatest: "Latest confirmation",
  recoveryProgressStopped: "Stopped",
  recoveryProgressSubmission: "Submit",
  recoveryProgressVerification: "Verification",
  selectionPending: "Submitting selection",
  selectionReceived: (eventId) => `Selection received · ${eventId}`,
  genericFailure: "Unable to load",
  failureDetail: (code) => code,
  partial: (excludedCount) => `Partial · ${excludedCount}`,
};

export function renderSurface(element: ReactElement) {
  return render(element);
}
