#!/usr/bin/env python3
"""Release-flow operational smoke check.

The default mode is read-only except for authenticated session creation. Pass
--demo-run only when you want to create a tracked demo release run. The script
never attempts live release dispatch.
"""

from __future__ import annotations

import argparse
import http.cookiejar
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any


JsonMap = dict[str, Any]


@dataclass
class SmokeResult:
    name: str
    ok: bool
    detail: str


class ApiError(RuntimeError):
    def __init__(self, method: str, path: str, status: int, body: str) -> None:
        super().__init__(f"{method} {path} failed with HTTP {status}: {body[:500]}")
        self.method = method
        self.path = path
        self.status = status
        self.body = body


class ApiClient:
    def __init__(self, api_base_url: str, timeout: float = 15.0) -> None:
        self.api_base_url = normalize_base_url(api_base_url)
        self.timeout = timeout
        self.cookies = http.cookiejar.CookieJar()
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(self.cookies))

    def request(
        self,
        method: str,
        path: str,
        payload: JsonMap | None = None,
        *,
        expected: tuple[int, ...] = (200,),
    ) -> JsonMap:
        body = None if payload is None else json.dumps(payload).encode()
        request = urllib.request.Request(
            api_url(self.api_base_url, path),
            data=body,
            method=method,
            headers={
                "accept": "application/json",
                "content-type": "application/json",
                "x-service-csrf": "same-origin",
            },
        )
        try:
            with self.opener.open(request, timeout=self.timeout) as response:
                raw = response.read().decode()
                status = int(response.status)
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode(errors="replace")
            status = int(exc.code)
        if status not in expected:
            raise ApiError(method, path, status, raw)
        return json.loads(raw) if raw else {}


def normalize_base_url(value: str) -> str:
    value = value.strip().rstrip("/")
    if not value:
        raise ValueError("api base URL is required")
    return value


def api_url(base_url: str, path: str) -> str:
    return f"{normalize_base_url(base_url)}/{path.lstrip('/')}"


def derive_api_base_url(args: argparse.Namespace) -> str:
    if args.api_base_url:
        return args.api_base_url
    base_url = args.base_url or os.getenv("BASE_URL", "")
    if not base_url:
        return os.getenv("API_BASE_URL", "")
    return f"{base_url.rstrip('/')}/api"


def build_demo_plan(applications: list[JsonMap]) -> JsonMap:
    if not applications:
        raise ValueError("at least one application is required for release-flow smoke")
    selected = applications[: min(3, len(applications))]
    steps = [demo_step(app, index, selected) for index, app in enumerate(selected)]
    return {
        "name": "Release flow smoke check",
        "description": "Generated by scripts/release_flow_smoke.py",
        "status": "draft",
        "settings": {
            "runtime_mode": "demo",
            "provider_mode": "dry_run",
            "execution_mode": "sequential_apply",
            "approval_policy": "manual_each_step",
            "failure_policy": "pause_for_operator",
            "rollback_policy": "safe_pr",
            "default_strategy": "rolling",
            "environment_order": ["sandbox", "staging", "production"],
            "require_diagnostics_pass": True,
        },
        "steps": steps,
    }


def demo_step(app: JsonMap, index: int, selected: list[JsonMap]) -> JsonMap:
    app_id = str(app.get("application_id") or app.get("id") or "")
    if not app_id:
        raise ValueError("application is missing application_id")
    return {
        "application_id": app_id,
        "name": str(app.get("name") or app_id),
        "position": index,
        "depends_on": [] if index == 0 else [str(selected[index - 1].get("application_id"))],
        "config": {
            "repo_ref": str(app.get("repo_ref") or ""),
            "branch": str(app.get("branch") or app.get("default_branch") or "main"),
            "manifest_path": str(app.get("manifest_path") or "deploy.yaml"),
            "cluster_id": str(app.get("cluster_id") or "target"),
            "environment": "sandbox",
            "namespace": "sandbox",
            "commit_sha": "release-flow-smoke",
            "image": "ghcr.io/example/release-flow-smoke:demo",
            "replicas": 1,
            "strategy": "rolling",
            "approval_gate": "inherit",
            "health_check_path": "/readyz",
            "timeout_seconds": 300,
        },
    }


def run_smoke(client: ApiClient, email: str, password: str, *, demo_run: bool) -> list[SmokeResult]:
    results: list[SmokeResult] = []
    health = client.request("GET", "/healthz")
    results.append(SmokeResult("healthz", health.get("status") == "ok", str(health)))
    ready = client.request("GET", "/readyz")
    results.append(SmokeResult("readyz", bool(ready), str(ready)))
    client.request("POST", "/auth/login", {"email": email, "password": password})
    session = client.request("GET", "/auth/session")
    results.append(SmokeResult("auth.session", bool(session.get("authenticated")), str(session)))
    applications = client.request("GET", "/applications").get("applications", [])
    if not isinstance(applications, list):
        raise ValueError("/applications response did not contain an applications list")
    results.append(SmokeResult("applications", bool(applications), f"{len(applications)} application(s)"))
    plans = client.request("GET", "/release-plans").get("plans", [])
    results.append(SmokeResult("release-plans", isinstance(plans, list), f"{len(plans)} plan(s)"))
    summary = client.request("GET", "/release-runs/summary")
    results.append(SmokeResult("release-runs.summary", "total_runs" in summary, str(summary)))
    plan = build_demo_plan(applications)
    preview = client.request("POST", "/release-plans/preview", plan).get("preview", {})
    results.append(
        SmokeResult(
            "release-plans.preview",
            bool(preview.get("executable")),
            str(preview.get("summary") or preview),
        )
    )
    if demo_run:
        run = client.request("POST", "/release-plans/start", plan).get("run", {})
        run_id = str(run.get("run_id") or "")
        side_effects = [
            step.get("details", {}).get("side_effects")
            for step in run.get("steps", [])
            if isinstance(step, dict)
        ]
        results.append(
            SmokeResult(
                "release-plans.start.demo",
                bool(run_id) and all(value is False for value in side_effects),
                run_id or str(run),
            )
        )
        if run_id:
            fetched = client.request("GET", f"/release-runs/{run_id}").get("run", {})
            results.append(
                SmokeResult(
                    "release-runs.get",
                    fetched.get("run_id") == run_id,
                    str(fetched.get("status") or fetched),
                )
            )
    return results


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-base-url", default=os.getenv("API_BASE_URL", ""))
    parser.add_argument("--base-url", default=os.getenv("BASE_URL", ""))
    parser.add_argument("--email", default=os.getenv("AUTH_EMAIL", ""))
    parser.add_argument("--password", default=os.getenv("AUTH_PASSWORD", ""))
    parser.add_argument("--timeout", type=float, default=float(os.getenv("SMOKE_TIMEOUT_SECONDS", "15")))
    parser.add_argument("--demo-run", action="store_true", help="create a tracked demo release run")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    api_base_url = derive_api_base_url(args)
    if not api_base_url or not args.email or not args.password:
        print("API_BASE_URL or BASE_URL, AUTH_EMAIL, and AUTH_PASSWORD are required", file=sys.stderr)
        return 2
    client = ApiClient(api_base_url, timeout=args.timeout)
    try:
        results = run_smoke(client, args.email, args.password, demo_run=args.demo_run)
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        return 1
    ok = all(item.ok for item in results)
    print(
        json.dumps(
            {"ok": ok, "api_base_url": client.api_base_url, "checks": [item.__dict__ for item in results]},
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
