"""발행 이벤트 body 계약(단일 출처, 도메인별 모듈).

네이밍 규칙:
- "<이벤트>Body" = 한 이벤트의 본문 전체(예: GitChangedBody).
- 접미사 없는 명사 = 본문 안에 끼워지는 값 객체(예: Manifest, Diff, Plan).
규칙: 입력은 Pydantic으로 검증, 출력(이 패키지)은 dataclass로 구성.

도메인별 base/gitops/command/rca 모듈로 분리, 여기서 전부
재노출 → `from packages.contracts.event_bus.bodies import X`로 사용.
"""

from __future__ import annotations

from domains.alert.events import (
    AlertDispatchedBody,
    AlertRejectedBody,
    AlertRequestedBody,
)
from domains.command.events import (
    CommandCompletedBody,
    CommandDispatchedBody,
    CommandDispatchReadyBody,
    CommandQueuedForAgentBody,
    CommandRejectedBody,
    CommandRequestedBody,
    LeaseMetadata,
    Plan,
    RetryPolicy,
    Route,
    RoutingConstraint,
)
from domains.gitops.events import (
    ApprovalGrantedBody,
    ApprovalRejectedBody,
    ApprovalRequestedBody,
    Diff,
    DiffAnalyzedBody,
    DiffDetectedBody,
    GitChangedBody,
    GitWebhookReceivedBody,
    Manifest,
    ManifestInvalidBody,
    ManifestRenderedBody,
    RenderedManifest,
    RenderedMetadata,
    RenderedSpec,
    WorkflowCreatedBody,
    WorkflowRunCompletedBody,
    WorkflowRunFailedBody,
    WorkflowRunStartedBody,
    WorkflowStepRecordedBody,
)
from domains.mail.events import EmailVerificationRequestedBody, EmailVerificationSentBody
from domains.rca.events import (
    ApprovalRecommendedBody,
    CauseCandidate,
    CauseEvaluation,
    ClusterEvidenceReceivedBody,
    DiffExplainedBody,
    Evidence,
    EvidenceBuiltBody,
    EvidenceBundle,
    EvidenceBundleBuiltBody,
    EvidenceItem,
    HealingActionDraft,
    IncidentDetectedBody,
    IncidentRecord,
    RcaActionRequiredBody,
    RcaAiFallbackRequestedBody,
    RcaBacklogItemCreatedBody,
    RcaCandidatesEvaluatedBody,
    RcaCandidatesPlannedBody,
    RcaCompletedBody,
    RcaReportDetail,
    RcaRuleMissing,
    RcaRuleMissingBody,
    RecoveryActionCandidate,
    RecoveryActionSelectedBody,
    RecoveryPlan,
    RecoveryPlannedBody,
    RecoverySelectionRequestedBody,
    RolloutDiagnosedBody,
    SafePrPatchPreparedBody,
)
from domains.scm.events import (
    SafePrCreatedBody,
    SafePrFailedBody,
    SafePrRequestedBody,
)
from domains.target.events import (
    ClusterDesiredStateChangedBody,
    ClusterDriftDetectedBody,
    ClusterReconcileCompletedBody,
    ClusterReconcileFailedBody,
    ClusterReconcileRequestedBody,
    ClusterReconcileStartedBody,
    TargetDesiredComponent,
    TargetDrift,
)
from packages.contracts.event_bus.bodies.base import EventBody, JsonObject

__all__ = [
    "AlertDispatchedBody",
    "AlertRejectedBody",
    "AlertRequestedBody",
    "ApprovalGrantedBody",
    "ApprovalRecommendedBody",
    "ApprovalRejectedBody",
    "ApprovalRequestedBody",
    "CauseCandidate",
    "CauseEvaluation",
    "ClusterDesiredStateChangedBody",
    "ClusterDriftDetectedBody",
    "ClusterEvidenceReceivedBody",
    "ClusterReconcileCompletedBody",
    "ClusterReconcileFailedBody",
    "ClusterReconcileRequestedBody",
    "ClusterReconcileStartedBody",
    "CommandCompletedBody",
    "CommandDispatchReadyBody",
    "CommandDispatchedBody",
    "CommandQueuedForAgentBody",
    "CommandRejectedBody",
    "CommandRequestedBody",
    "Diff",
    "DiffAnalyzedBody",
    "DiffDetectedBody",
    "DiffExplainedBody",
    "EmailVerificationRequestedBody",
    "EmailVerificationSentBody",
    "EventBody",
    "Evidence",
    "EvidenceBuiltBody",
    "EvidenceBundle",
    "EvidenceBundleBuiltBody",
    "EvidenceItem",
    "GitChangedBody",
    "GitWebhookReceivedBody",
    "HealingActionDraft",
    "IncidentDetectedBody",
    "IncidentRecord",
    "JsonObject",
    "LeaseMetadata",
    "Manifest",
    "ManifestInvalidBody",
    "ManifestRenderedBody",
    "Plan",
    "RcaActionRequiredBody",
    "RcaAiFallbackRequestedBody",
    "RcaBacklogItemCreatedBody",
    "RcaCandidatesEvaluatedBody",
    "RcaCandidatesPlannedBody",
    "RcaCompletedBody",
    "RcaReportDetail",
    "RcaRuleMissing",
    "RcaRuleMissingBody",
    "RecoveryActionCandidate",
    "RecoveryActionSelectedBody",
    "RecoveryPlan",
    "RecoveryPlannedBody",
    "RecoverySelectionRequestedBody",
    "RenderedManifest",
    "RenderedMetadata",
    "RenderedSpec",
    "RetryPolicy",
    "RolloutDiagnosedBody",
    "Route",
    "RoutingConstraint",
    "SafePrCreatedBody",
    "SafePrFailedBody",
    "SafePrPatchPreparedBody",
    "SafePrRequestedBody",
    "TargetDesiredComponent",
    "TargetDrift",
    "WorkflowCreatedBody",
    "WorkflowRunCompletedBody",
    "WorkflowRunFailedBody",
    "WorkflowRunStartedBody",
    "WorkflowStepRecordedBody",
]
