apiVersion: v1
kind: Secret
metadata:
  name: oauth-provider-secrets
  namespace: eda-management
type: Opaque
stringData:
  GITHUB_CLIENT_ID: replace-me
  GITHUB_CLIENT_SECRET: replace-me
  GOOGLE_CLIENT_ID: replace-me
  GOOGLE_CLIENT_SECRET: replace-me

