from __future__ import annotations

DEFAULT_DATABASE_URL = "postgresql://service:service@postgresql:5432/service"
DEFAULT_NATS_URL = "nats://nats:4222"
DEFAULT_REDIS_URL = "redis://redis:6379/0"
DEFAULT_SERVICE_NAME = "service"
DEFAULT_HTTP_PORT = "8000"
DEFAULT_TARGET_CLUSTER_ID = "target-cluster-01"
DEFAULT_EVIDENCE_INTERVAL_SECONDS = "10"
DEFAULT_SESSION_TTL_SECONDS = "86400"
SERVICE_NAME_ENV = "SERVICE_NAME"
LOCAL_USER_ID = "local-user"
SANDBOX_NAMESPACE = "sandbox"
GITHUB_PROVIDER = "github"
REQUIRED_GITHUB_SCOPE = "repo"
SESSION_COOKIE_NAME = "service_session"
