import type { IssuesFailureCode } from "../../features/issues/issuesContract";
import type { IssuesSurfaceCopy } from "../../features/issues/issuesSurfaceContract";
import {
  issueAuditEventLabel,
  issueAuditStageLabel,
} from "../../features/issues/issueAuditPresentation";
import { evidenceCollectorLabel } from "../../features/issues/issueEvidencePresentation";
import { ISSUE_STATUS_MESSAGE } from "../../features/issues/issuePresentation";
import type { MessageKey, TranslationFunction } from "../../shared/i18n/types";
import {
  evidenceKindLabel,
  evidenceRecordLabel,
  evidenceSourceLabel,
  evidenceSummaryLabel,
  formatAuditTime,
  translateOperationalValue,
} from "./issuesPageEvidenceCopy";

const FAILURE_MESSAGE: Record<IssuesFailureCode, MessageKey> = {
  unauthorized: "issues.surface.failure.unauthorized",
  forbidden: "issues.surface.failure.forbidden",
  "invalid-request": "issues.surface.failure.invalidRequest",
  "invalid-response": "issues.surface.failure.invalidResponse",
  "not-found": "issues.surface.failure.notFound",
  offline: "issues.surface.failure.offline",
  "rate-limited": "issues.surface.failure.rateLimited",
  unavailable: "issues.surface.failure.unavailable",
  error: "issues.surface.failure.error",
};

const RECOVERY_CARD_MESSAGE: Record<
  Parameters<IssuesSurfaceCopy["recoveryCardProgress"]>[0],
  MessageKey
> = {
  active: "issues.recovery.card.active",
  approval: "issues.recovery.card.approval",
  completed: "issues.recovery.card.completed",
  failed: "issues.recovery.card.failed",
};

const CAUSE_MESSAGE: Record<string, MessageKey> = {
  oom_killed: "issues.cause.oomKilled",
  memory_limit_too_low: "issues.cause.oomKilled",
  node_affinity_or_taint_mismatch: "issues.cause.nodePlacementMismatch",
  node_selector_mismatch: "issues.cause.nodePlacementMismatch",
  untolerated_taint: "issues.cause.nodePlacementMismatch",
  upstream_unavailable: "issues.cause.ingressUnavailable",
  backend_readiness_failure: "issues.cause.ingressUnavailable",
  insufficient_evidence: "issues.cause.insufficientEvidence",
  wrong_image_tag: "issues.cause.wrongImageTag",
  bad_image_rollout: "issues.cause.wrongImageTag",
  registry_unavailable: "issues.cause.registryUnavailable",
};

const EVIDENCE_NAME_MESSAGE: Record<string, MessageKey> = {
  broken_image_startup_log: "issues.evidence.name.brokenImageStartupLog",
  cluster_resource_state: "issues.evidence.name.clusterResourceState",
  config_error_log: "issues.evidence.name.configErrorLog",
  current_workload_snapshots: "issues.evidence.name.currentWorkloadSnapshots",
  dependency_error_log: "issues.evidence.name.dependencyErrorLog",
  port_bind_failure_signal: "issues.evidence.name.portBindFailureSignal",
  related_logs: "issues.evidence.name.relatedLogs",
  related_traces: "issues.evidence.name.relatedTraces",
  startup_crash_signal: "issues.evidence.name.startupCrashSignal",
  startup_permission_denied_signal: "issues.evidence.name.startupPermissionDeniedSignal",
  telemetry_metrics: "issues.evidence.name.telemetryMetrics",
};

export function createIssuesCopy(
  t: TranslationFunction,
  formatNumber: (value: number | bigint, options?: Intl.NumberFormatOptions) => string,
  formatDate: (value: Date | number, options?: Intl.DateTimeFormatOptions) => string,
): IssuesSurfaceCopy {
  return {
    listLabel: t("issues.surface.list"),
    listEmpty: t("issues.surface.listEmpty"),
    listLoading: t("issues.surface.listLoading"),
    listCount: (count) => formatNumber(count),
    listMatchedCount: (returned, matched) => t("issues.surface.matchedCount", {
      returned: formatNumber(returned),
      matched: formatNumber(matched),
    }),
    visibilityLabel: t("issues.surface.visibility.label"),
    visibilityPartial: t("issues.surface.visibility.partial"),
    visibilityRestricted: t("issues.surface.visibility.restricted"),
    listBrowseResources: t("issues.empty.resources"),
    listBrowseAlerts: t("issues.empty.alerts"),
    detailLabel: t("issues.surface.detail"),
    detailEmpty: t("issues.surface.detailEmpty"),
    detailLoading: t("issues.surface.detailLoading"),
    detailClose: t("issues.detail.close"),
    detailExpand: t("issues.detail.expand"),
    detailCollapse: t("issues.detail.collapse"),
    auditLabel: t("issues.audit.title"),
    auditUnavailable: t("issues.audit.unavailable"),
    auditRoot: t("issues.audit.root"),
    auditCause: (causationId) => t("issues.audit.cause", { causationId }),
    auditEvent: (subject) => issueAuditEventLabel(subject, t),
    auditStage: (stage) => issueAuditStageLabel(stage, t),
    auditPayload: t("issues.audit.payload"),
    auditLoadMore: t("issues.audit.loadMore"),
    auditLoadingMore: t("issues.audit.loadingMore"),
    auditTimeUnknown: t("issues.audit.timeUnknown"),
    auditTime: (value) => formatAuditTime(value, formatDate, t),
    recentChangesLabel: t("issues.recentChanges.title"),
    recentChangesUnavailable: t("issues.recentChanges.unavailable"),
    recentChangesPullRequest: t("issues.recentChanges.pullRequest"),
    recentChangesTime: (value) => formatAuditTime(value, formatDate, t),
    recentChangesImageBeforeLabel: t("issues.recentChanges.imageBefore"),
    recentChangesImageAfterLabel: t("issues.recentChanges.imageAfter"),
    recentChangesCommitLabel: t("issues.recentChanges.commit"),
    recentChangesRepositoryLabel: t("issues.recentChanges.repository"),
    recentChangesWorkflowLabel: t("issues.recentChanges.workflow"),
    evidenceLabel: t("issues.surface.evidence"),
    evidenceRecordLabel: (summary) => evidenceRecordLabel(summary, t),
    evidenceKindLabel: (kind) => evidenceKindLabel(kind, t),
    evidenceSourceLabel: (source) => evidenceSourceLabel(source, t),
    evidenceCollectorLabel: (collector) => /^cluster-agent(?:@unknown)?$/i.test(collector.trim())
      ? t("issues.evidence.collector.clusterAgent")
      : evidenceCollectorLabel(collector),
    evidenceSummaryLabel: (source, summary) => evidenceSummaryLabel(
      source,
      summary,
      t,
      formatNumber,
    ),
    reportsLabel: t("issues.surface.reports"),
    reportsEmpty: t("issues.surface.reportsEmpty"),
    recoveryLabel: t("issues.surface.recovery"),
    sectionLoading: t("issues.surface.sectionLoading"),
    sectionEmpty: t("issues.surface.sectionEmpty"),
    evidenceUnavailable: t("issues.surface.evidenceUnavailable"),
    reportsUnavailable: t("issues.surface.reportsUnavailable"),
    recoveryUnavailable: t("issues.surface.recoveryUnavailable"),
    refresh: t("common.action.refresh"),
    status: t("issues.surface.status"),
    statusLabel: (status) => translateOperationalValue(status, ISSUE_STATUS_MESSAGE, t),
    lifecycleOpen: t("issues.lifecycle.open"),
    lifecycleClosed: t("issues.lifecycle.closed"),
    actionReviewRequired: t("issues.action.reviewRequired"),
    actionReviewAgainRequired: t("issues.action.reviewAgainRequired"),
    actionAutoApprovalAvailable: t("issues.action.autoApprovalAvailable"),
    scope: t("issues.surface.scope"),
    namespaceSuffix: t("issues.surface.namespaceSuffix"),
    cluster: t("issues.context.cluster"),
    namespace: t("issues.context.namespace"),
    resourceKind: t("issues.context.resourceKind"),
    analysisComplete: t("issues.analysis.complete"),
    severityFilterLabel: t("issues.severity.filter"),
    severityFilterAll: t("issues.severity.all"),
    severityCritical: t("issues.severity.critical"),
    severityWarning: t("issues.severity.warning"),
    severityHealthy: t("issues.severity.healthy"),
    severityTooltip: (value) => t("issues.severity.tooltip", { value }),
    valueUnknown: t("issues.value.unknown"),
    recoveryCardProgress: (state) => t(RECOVERY_CARD_MESSAGE[state]),
    situationSummary: t("issues.summary.situation"),
    situationSummaryText: (symptom, cause, status) => t("issues.summary.text", {
      cause: cause || t("issues.value.unknown"),
      status,
      symptom,
    }),
    noAdditionalAction: t("issues.action.none"),
    impactScope: t("issues.report.impactScope"),
    finalJudgement: t("issues.report.finalJudgement"),
    finalCause: t("issues.report.finalCause"),
    evidenceSummaryTitle: t("issues.report.evidenceSummary"),
    evidenceDetailsTitle: t("issues.report.evidenceDetails"),
    recommendedActionTitle: t("issues.report.recommendedAction"),
    viewRecoveryAction: t("issues.report.viewRecovery"),
    actionRisk: t("issues.report.actionRisk"),
    time: t("issues.report.time"),
    evidenceCoverage: (confirmed, total) => t("issues.report.evidenceCoverage", {
      confirmed: formatNumber(confirmed),
      total: formatNumber(total),
    }),
    causeCandidates: t("issues.report.causeCandidates"),
    itemCount: (count) => t("issues.count.items", { count: formatNumber(count) }),
    finalJudgementText: (cause, symptom) => t("issues.report.judgementText", { cause, symptom }),
    memoryRecommendation: t("issues.report.memoryRecommendation"),
    reviewRecoveryPlan: t("issues.report.reviewRecovery"),
    evidenceNameLabel: (name) => translateOperationalValue(name, EVIDENCE_NAME_MESSAGE, t),
    recommendedRecoveryActions: t("issues.recovery.recommendedActions"),
    otherRecoveryCandidates: t("issues.recovery.otherCandidates"),
    recommendationReason: t("issues.recovery.recommendationReason"),
    expectedOutcome: t("issues.recovery.expectedOutcome"),
    riskExplanation: t("issues.recovery.riskExplanation"),
    actionToRun: t("issues.recovery.actionToRun"),
    validationChecks: t("issues.recovery.validationChecks"),
    rollbackAction: t("issues.recovery.rollbackAction"),
    selectRecoveryAction: t("issues.recovery.selectAction"),
    riskLabel: (severity) => {
      const normalized = severity?.trim().toLowerCase();
      if (normalized === "critical") return t("issues.risk.critical");
      if (normalized === "medium" || normalized === "warning") return t("issues.risk.medium");
      if (normalized === "low" || normalized === "info") return t("issues.risk.low");
      return t("issues.value.unknown");
    },
    severityLabel: (severity) => t(
      severity === "critical"
        ? "issues.severity.critical"
        : "issues.severity.warning",
    ),
    causeLabel: (cause) => translateOperationalValue(cause, CAUSE_MESSAGE, t),
    target: t("issues.table.target"),
    updated: t("issues.table.updated"),
    confidence: t("issues.detail.meta.confidence"),
    symptom: t("issues.detail.section.symptom"),
    supportingEvidence: t("issues.detail.section.evidence"),
    missingEvidence: t("issues.detail.section.missingEvidence"),
    rootCause: t("issues.surface.rootCause"),
    recommended: t("issues.surface.recommended"),
    narrativeLabel: t("issues.report.narrative.label"),
    narrativeSummary: t("issues.report.narrative.summary"),
    narrativeImpact: t("issues.report.narrative.impact"),
    narrativeReasoning: t("issues.report.narrative.reasoning"),
    narrativeRecommendedAction: t("issues.report.narrative.recommendedAction"),
    narrativeRecurrencePrevention: t("issues.report.narrative.recurrencePrevention"),
    narrativeLimitations: t("issues.report.narrative.limitations"),
    approvalRequired: t("issues.surface.approvalRequired"),
    recoveryProgressAccepted: t("issues.recovery.progress.accepted"),
    recoveryProgressApproval: t("issues.recovery.progress.approval"),
    recoveryProgressApprovalWaiting: t("issues.recovery.progress.approvalWaiting"),
    recoveryProgressCompletion: t("issues.recovery.progress.completion"),
    recoveryProgressExecution: t("issues.recovery.progress.execution"),
    recoveryProgressFailed: t("issues.recovery.progress.failed"),
    recoveryProgressLabel: t("issues.recovery.progress.label"),
    recoveryProgressLatest: t("issues.recovery.progress.latest"),
    recoveryProgressStopped: t("issues.recovery.progress.stopped"),
    recoveryProgressSubmission: t("issues.recovery.progress.submission"),
    recoveryProgressVerification: t("issues.recovery.progress.verification"),
    selectionPending: t("issues.surface.selectionPending"),
    selectionReceived: (eventId) => t("issues.surface.selectionReceived", { eventId }),
    genericFailure: t("issues.surface.genericFailure"),
    failureDetail: (code) => t(FAILURE_MESSAGE[code]),
    partial: (excludedCount) => t("issues.surface.partial", {
      count: formatNumber(excludedCount),
    }),
  };
}
