from __future__ import annotations

from typing import Final


class Gateway:
    ACCEPTED: Final[str] = "accepted"
    ACCOUNT: Final[str] = "account"
    ACTION: Final[str] = "action"
    AGENT_ID: Final[str] = "agent_id"
    APPLIED: Final[str] = "applied"
    AUTHORIZATION_URL: Final[str] = "authorization_url"
    AUTHENTICATED: Final[str] = "authenticated"
    CAPABILITIES: Final[str] = "capabilities"
    CARDS: Final[str] = "cards"
    CLUSTER_ID: Final[str] = "cluster_id"
    COMMAND: Final[str] = "command"
    COMMAND_ID: Final[str] = "command_id"
    DEAD_LETTER_ID: Final[str] = "dead_letter_id"
    DEAD_LETTERS: Final[str] = "dead_letters"
    ERROR: Final[str] = "error"
    EVENT: Final[str] = "event"
    MESSAGE: Final[str] = "message"
    NAMESPACE: Final[str] = "namespace"
    PROVIDER: Final[str] = "provider"
    PROVIDER_USER: Final[str] = "provider_user"
    REPLAY_EVENT: Final[str] = "replay_event"
    REQUESTED_BY: Final[str] = "requested_by"
    RESULT: Final[str] = "result"
    ROLES: Final[str] = "roles"
    SCOPES: Final[str] = "scopes"
    SERVICE: Final[str] = "service"
    SESSION: Final[str] = "session"
    SESSION_TOKEN: Final[str] = "session_token"
    STATE: Final[str] = "state"
    STATUS: Final[str] = "status"
    STATUS_CONNECTED: Final[str] = "connected"
    STATUS_OK: Final[str] = "ok"
    STATUS_OPEN: Final[str] = "open"
    STATUS_READY: Final[str] = "ready"
    STATUS_REPLAYED: Final[str] = "replayed"
    TOKEN_REF: Final[str] = "token_ref"
    USER_ID: Final[str] = "user_id"
