from __future__ import annotations

TARGET_AGENT_SERVICE_NAME = "target-cluster-agent"

DEFAULT_MANAGEMENT_BASE_URL = "http://localhost:18080"
DEFAULT_PROMETHEUS_BASE_URL = "http://prometheus.target.svc:9090"
DEFAULT_LOKI_BASE_URL = "http://loki-gateway.target.svc"
DEFAULT_TEMPO_BASE_URL = "http://tempo.target.svc:3200"
DEFAULT_OTEL_SERVICE_NAME = "target-cluster-agent"
DEFAULT_OTEL_TRACES_ENDPOINT = "http://opentelemetry-collector.target.svc:4318/v1/traces"

MANAGEMENT_BASE_URL_ENV = "MANAGEMENT_BASE_URL"
PROMETHEUS_BASE_URL_ENV = "PROMETHEUS_BASE_URL"
LOKI_BASE_URL_ENV = "LOKI_BASE_URL"
TEMPO_BASE_URL_ENV = "TEMPO_BASE_URL"
OTEL_SERVICE_NAME_ENV = "OTEL_SERVICE_NAME"
OTEL_TRACES_ENDPOINT_ENV = "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"

TARGET_CLUSTER_ID_ENV = "TARGET_CLUSTER_ID"
EVIDENCE_INTERVAL_ENV = "EVIDENCE_INTERVAL_SECONDS"
EVIDENCE_QUEUE_DB_PATH_ENV = "EVIDENCE_QUEUE_DB_PATH"
EVIDENCE_PROVIDER_WORKERS_ENV = "EVIDENCE_PROVIDER_WORKERS"
EVIDENCE_FAILURE_POLICY_ENV = "EVIDENCE_FAILURE_POLICY"

HTTP_TIMEOUT_SECONDS = 20
PROMETHEUS_TIMEOUT_SECONDS = 5
LOKI_TIMEOUT_SECONDS = 5
LOKI_QUERY_LIMIT = 20
TEMPO_TIMEOUT_SECONDS = 5
TEMPO_QUERY_LIMIT = 20
COMMAND_POLL_TIMEOUT_SECONDS = 15

COMMAND_EXECUTION_DELAY_SECONDS = 2
REGISTER_RETRY_DELAY_SECONDS = 3
COMMAND_RETRY_DELAY_SECONDS = 3
EVIDENCE_TASK_LEASE_SECONDS = 60
DEFAULT_EVIDENCE_QUEUE_DB_PATH = "/data/evidence-queue.db"
DEFAULT_EVIDENCE_PROVIDER_WORKERS = "metrics=1,logs=1,traces=1"
DEFAULT_EVIDENCE_FAILURE_POLICY = "allow_partial"

HOSTNAME_ENV = "HOSTNAME"
DEFAULT_AGENT_ID = "target-agent"
AGENT_CAPABILITIES = ["collector", "command_receiver"]

COMMAND_COMPLETED_STATUS = "completed"
COMMAND_FAILED_STATUS = "failed"
COMMAND_RESULT_MESSAGE = "Kubernetes action applied in sandbox namespace"

QUERY_RUN_ACTION = "telemetry.query.run"
