from __future__ import annotations

TARGET_AGENT_SERVICE_NAME = "target-cluster-agent"

DEFAULT_MANAGEMENT_BASE_URL = "http://localhost:18080"
DEFAULT_PROMETHEUS_BASE_URL = "http://prometheus.target.svc:9090"
DEFAULT_LOKI_BASE_URL = "http://loki-gateway.target.svc"
DEFAULT_TEMPO_BASE_URL = "http://tempo.target.svc:3200"
DEFAULT_OTEL_SERVICE_NAME = "target-cluster-agent"
DEFAULT_OTEL_TRACES_ENDPOINT = "http://opentelemetry-collector.target.svc:4318/v1/traces"

MANAGEMENT_BASE_URL_ENV = "MANAGEMENT_BASE_URL"
PROMETHEUS_BASE_URL_ENV = "PROMETHEUS_BASE_URL"
LOKI_BASE_URL_ENV = "LOKI_BASE_URL"
TEMPO_BASE_URL_ENV = "TEMPO_BASE_URL"
OTEL_SERVICE_NAME_ENV = "OTEL_SERVICE_NAME"
OTEL_TRACES_ENDPOINT_ENV = "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"

TARGET_CLUSTER_ID_ENV = "TARGET_CLUSTER_ID"
CLUSTER_ROLE_ENV = "CLUSTER_ROLE"
BOOTSTRAP_MODE_ENV = "BOOTSTRAP_MODE"
EVIDENCE_INTERVAL_ENV = "EVIDENCE_INTERVAL_SECONDS"
EVIDENCE_QUEUE_DB_PATH_ENV = "EVIDENCE_QUEUE_DB_PATH"
AGENT_CONTROL_DB_PATH_ENV = "AGENT_CONTROL_DB_PATH"
EVIDENCE_PROVIDER_WORKERS_ENV = "EVIDENCE_PROVIDER_WORKERS"
EVIDENCE_PROVIDER_MAX_WORKERS_ENV = "EVIDENCE_PROVIDER_MAX_WORKERS"
EVIDENCE_FAILURE_POLICY_ENV = "EVIDENCE_FAILURE_POLICY"
WORKLOAD_CONTROLLER_INTERVAL_ENV = "WORKLOAD_CONTROLLER_INTERVAL_SECONDS"
WORKLOAD_QUEUE_AGE_TARGET_ENV = "WORKLOAD_QUEUE_AGE_TARGET_SECONDS"
POLICY_SYNC_INTERVAL_ENV = "POLICY_SYNC_INTERVAL_SECONDS"
RECONCILE_INTERVAL_ENV = "RECONCILE_INTERVAL_SECONDS"
TELEMETRY_QUERY_PATH_ENV = "TELEMETRY_QUERY_PATH"
KUBERNETES_SERVICE_HOST_ENV = "KUBERNETES_SERVICE_HOST"
KUBERNETES_SERVICE_PORT_ENV = "KUBERNETES_SERVICE_PORT"

HTTP_TIMEOUT_SECONDS = 20
PROMETHEUS_TIMEOUT_SECONDS = 5
LOKI_TIMEOUT_SECONDS = 5
LOKI_QUERY_LIMIT = 20
TEMPO_TIMEOUT_SECONDS = 5
TEMPO_QUERY_LIMIT = 20
COMMAND_POLL_TIMEOUT_SECONDS = 15

COMMAND_EXECUTION_DELAY_SECONDS = 2
REGISTER_RETRY_DELAY_SECONDS = 3
COMMAND_RETRY_DELAY_SECONDS = 3
EVIDENCE_TASK_LEASE_SECONDS = 60
DEFAULT_EVIDENCE_QUEUE_DB_PATH = "/data/evidence-queue.db"
DEFAULT_AGENT_CONTROL_DB_PATH = "/data/agent-control.db"
DEFAULT_EVIDENCE_PROVIDER_WORKERS = "metrics=1,logs=1,traces=1"
DEFAULT_EVIDENCE_PROVIDER_MAX_WORKERS = "metrics=3,logs=3,traces=3"
DEFAULT_EVIDENCE_FAILURE_POLICY = "allow_partial"
DEFAULT_WORKLOAD_CONTROLLER_INTERVAL_SECONDS = 5
DEFAULT_WORKLOAD_QUEUE_AGE_TARGET_SECONDS = 15
DEFAULT_POLICY_SYNC_INTERVAL_SECONDS = 15
DEFAULT_RECONCILE_INTERVAL_SECONDS = 30
DEFAULT_TELEMETRY_QUERY_PATH = "services/target-cluster-agent/queries"
DEFAULT_CLUSTER_ROLE = "target"
DEFAULT_BOOTSTRAP_MODE = "target"
DEFAULT_KUBERNETES_SERVICE_HOST = "kubernetes.default.svc"
DEFAULT_KUBERNETES_SERVICE_PORT = "443"
KUBERNETES_SERVICEACCOUNT_DIR = "/var/run/secrets/kubernetes.io/serviceaccount"
KUBERNETES_SERVICEACCOUNT_TOKEN_PATH = f"{KUBERNETES_SERVICEACCOUNT_DIR}/token"
KUBERNETES_SERVICEACCOUNT_CA_CERT_PATH = f"{KUBERNETES_SERVICEACCOUNT_DIR}/ca.crt"
KUBERNETES_API_TIMEOUT_SECONDS = 5

HOSTNAME_ENV = "HOSTNAME"
DEFAULT_AGENT_ID = "target-agent"
AGENT_CAPABILITIES = ["collector", "command_receiver"]

COMMAND_COMPLETED_STATUS = "completed"
COMMAND_FAILED_STATUS = "failed"
COMMAND_RESULT_MESSAGE = "Kubernetes action applied in sandbox namespace"

QUERY_RUN_ACTION = "telemetry.query.run"
QUERY_REGISTER_ACTION = "telemetry.query.register"
QUERY_IMPORT_ACTION = "telemetry.query.import"
